### ISSUE TITLE
Question on negatives reweight implementation

### ISSUE THREAD

**Issue by qiyan98** [joshr17/HCL#1]
Hi,

I have some difficulties understanding the hard sampling objectives implemented for image tasks.
In your code, the reweight is carried out based on `mean` of `imp` rather than the raw `neg` inner products, which seems to be different than the pseudo-code on line 16, Figure 7 in your paper.
https://github.com/joshr17/HCL/blob/5bfa3009311c8926a58c15fbe27c8f9cce1f896d/image/main.py#L44

I wonder which one is correct. To use `imp.mean(dim=-1)` or `neg.mean(dim=-1)` as the denominator?

Many thanks,
Qi Yan

**Comment by joshr17** [comment]
Thanks for the question.

Good catch! The code is correct and the pseudo-code is slightly wrong. I'll make the fix in the paper. 

The only reason the pseudo-code is included in the appendix is to emphasize how little code in the objective needs to be changed in order to implement the hard negative sampling. This main point remains unaffected by the typos in the pseudo-code.

If ever in doubt, see Section 3 of the paper for the derivation of the method, that should make everything clear.

Best,

Josh

**Comment by qiyan98** [comment]
Thanks for your helpful explanation!
